Repository yoanpetrov02/todo-app, pull requests merged in 2024-01, with the labels that each got.

#27 Create UserService interface.
  src/main/java/com/tudu/todoapp/rest/controllers/UserController.java
  src/main/java/com/tudu/todoapp/services/implementations/UserServiceImpl.java
  src/main/java/com/tudu/todoapp/services/interfaces/UserService.java
Labels: enhancement

#28 Create BoardService interface and implement it.
  src/main/java/com/tudu/todoapp/services/implementations/BoardServiceImpl.java
  src/main/java/com/tudu/todoapp/services/interfaces/BoardService.java
Labels: enhancement, feature

#30 Create BoardController with basic endpoints.
  src/main/java/com/tudu/todoapp/rest/controllers/BoardController.java
  src/main/java/com/tudu/todoapp/services/implementations/BoardServiceImpl.java
Labels: feature

#32 21 create todoitem controller with basic endpoints
  src/main/java/com/tudu/todoapp/rest/controllers/ToDoItemController.java
  src/main/java/com/tudu/todoapp/services/implementations/ToDoItemServiceImpl.java
  src/main/java/com/tudu/todoapp/services/interfaces/ToDoItemService.java
Labels: normal-priority
